CREATE DATABASE Mecanica;
USE Mecanica;

CREATE TABLE Servicos (
ID_Servico INT NOT NULL PRIMARY KEY,
Valor DECIMAL(7,2) NOT NULL,
Nome_Servico VARCHAR(50) NOT NULL,
Descricao TEXT NOT NULL
);

CREATE TABLE Veiculos (
Placa_veiculo VARCHAR(10) NOT NULL PRIMARY KEY,
Modelo VARCHAR(20) NOT NULL,
Marca VARCHAR(20) NOT NULL,
ID_Cliente INT NOT NULL
);

CREATE TABLE Ordens_Servico (
ID_Ordem INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Data_ordem DATETIME NOT NULL,
Total DECIMAL(32, 2) NOT NULL,
Placa_veiculo VARCHAR(10) NOT NULL,
ID_Cliente INT NOT NULL,
FOREIGN KEY(Placa_veiculo) REFERENCES Veiculos (Placa_veiculo)
);

CREATE TABLE Mecanicos (
ID_Mecanico INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Nome_Mecanico VARCHAR(100) NOT NULL,
CPF VARCHAR(20) NOT NULL UNIQUE,
Especialidade VARCHAR(20) NOT NULL,
Salario DECIMAL(10,2) NOT NULL
);

CREATE TABLE Clientes (
ID_Cliente INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
CPF VARCHAR(15) NOT NULL UNIQUE,
Telefone VARCHAR(19) NOT NULL,
Nome_cliente VARCHAR(100) NOT NULL
);

CREATE TABLE Estoque (
Codigo INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Quantidade INT NOT NULL,
ID_Peca INT NOT NULL
);

CREATE TABLE Pecas (
ID_Peca INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
Tipo_peca VARCHAR(20) NOT NULL,
Nome_peca VARCHAR(100) NOT NULL,
Descricao TEXT NOT NULL
);

CREATE TABLE OS_Mecanicos (
ID_Ordem INT NOT NULL,
ID_Mecanico INT NOT NULL,
FOREIGN KEY(ID_Ordem) REFERENCES Ordens_Servico (ID_Ordem),
FOREIGN KEY(ID_Mecanico) REFERENCES Mecanicos (ID_Mecanico)
);

CREATE TABLE OS_Servicos (
ID_Ordem INT NOT NULL,
ID_Servico INT NOT NULL,
FOREIGN KEY(ID_Ordem) REFERENCES Ordens_Servico (ID_Ordem),
FOREIGN KEY(ID_Servico) REFERENCES Servicos (ID_Servico)
);

CREATE TABLE Peca_Servicos (
ID_Peca INT NOT NULL,
ID_Servico INT NOT NULL,
FOREIGN KEY(ID_Peca) REFERENCES Pecas (ID_Peca),
FOREIGN KEY(ID_Servico) REFERENCES Servicos (ID_Servico)
);

ALTER TABLE Veiculos ADD FOREIGN KEY(ID_Cliente) REFERENCES Clientes (ID_Cliente);
ALTER TABLE Ordens_Servico ADD FOREIGN KEY(ID_Cliente) REFERENCES Clientes (ID_Cliente);
ALTER TABLE Estoque ADD FOREIGN KEY(ID_Peca) REFERENCES Pecas (ID_Peca);
